---
title: "Lineages"
output: html_document
date: '2023-01-23'
---
```{r}
#installed.packages('ggplot2')
library('ggplot2')
library(dplyr)
library(tidyverse)
library(anytime)
theme_set(theme_bw())
```


## LIFE SPAN
```{r}
samples <- read.csv2('../data/all_samples.tsv', sep='\t', header = TRUE)

samples$Nextstrain_clade
lineage <- samples[c('gisaid_epi_isl','continent','country','Nextstrain_clade','Nextclade_pango','date')]
lineage$Date <- anytime::anydate(lineage$date)
lineage <- lineage[lineage$Nextstrain_clade!='recombinant',]

#boxplot
ggplot(data = lineage, aes(x = Date, y = Nextstrain_clade,  fill=Nextstrain_clade))+
  geom_boxplot(color='black',width=0.5)+
  labs(x='Time',y='SARS-CoV-2 Clades')

#boxplot
ggplot(data = lineage, aes(x = Date, y = Nextstrain_clade,  fill=Nextstrain_clade))+
  geom_boxplot(color='black',width=0.5)+
  facet_wrap(.~continent, ncol=2, scales = 'free')+
  labs(x='Time',y='SARS-CoV-2 Clades')

```
## 
```{r}
# make dates as days
## get appearance of lineage by cont
pang_app <- lineage %>%
  group_by(Nextclade_pango) %>%
  arrange(Date) %>%
  filter(row_number()==1 )

ggplot(pang_app, aes(x=Date))+
  geom_histogram(aes(y = ..density..), binwidth = 30, fill = "white",color='black')+
  geom_density(adjust = 1, color = 'blue', fill='blue',alpha=.2)+
  labs(y = 'Density (Lineage appearence date)')

pang_app$YM <- zoo::as.yearmon(anytime::anydate(pang_app$date))

pang_appT <- as.data.frame(table(pang_app$YM))
pang_appT$Date <- zoo::as.yearmon(pang_appT$Var1)
str(pang_appT)
ggplot(pang_appT, aes(x=anytime::anydate(Date), y=Freq))+
  geom_bar(stat='identity', fill = 'lightblue')+
  ggplot2::coord_cartesian(ylim = c(0,NA) )+
  geom_smooth( se = FALSE, span=.35)
  labs(y = 'Density (Lineage appearence date)')

```

#### 
```{r}
# make dates as days
## get appearance of mutation by cont
mutations <- read.csv('../data/aa_mutations.csv', header=FALSE)
colnames(mutations)[1] = 'id'
library(reshape2)
mutation <- melt(mutations, 'id')[c('id','value')]
colnames(mutation) <- c('gisaid_epi_isl','Mutation')
Mutation <- merge(mutation, samples, by='gisaid_epi_isl')

Mutation$Date <- anytime::anydate(Mutation$date)
muts_app <- Mutation %>%
  group_by(Mutation) %>%
  arrange(Date) %>%
  filter(row_number()==1 )

ggplot(muts_app, aes(x=Date))+
  geom_histogram(aes(y = ..density..), binwidth = 30, fill = "white",color='black')+
  geom_density(adjust = 3.5, color = 'red', fill='red',alpha=.2)+
  labs(y = 'Density (Mutation appearence date)', x = 'Date (Months)')

muts_app$YM <- zoo::as.yearmon(anytime::anydate(muts_app$Date))
muts_appT <- as.data.frame(table(muts_app$YM))
muts_appT$Date <- zoo::as.yearmon(muts_appT$Var1)
str(muts_appT)

ggplot(muts_appT, aes(x=anytime::anydate(Date), y=Freq))+
  geom_bar(stat='identity', fill = 'lightblue')+
  geom_smooth( se = FALSE, span=.35)+
  ggplot2::coord_cartesian(ylim = c(0,NA) )+
  labs(y = 'Density (Lineage appearence date)')

ggplot(pang_appT, aes(x=Date, y=Freq))+
  geom_bar(data = muts_appT, alpha=.4, aes(y = Freq/10), stat='identity', fill = 'red')+
  geom_bar(stat='identity', fill = 'lightblue', alpha=.5)+
  geom_smooth( se = FALSE, span=.35, color = 'blue')+
  geom_smooth(data = muts_appT, aes(y = Freq/10), se = FALSE, span=.5, color = 'red')+
  ggplot2::coord_cartesian(ylim = c(0,NA) )+
  labs(y = 'Density (Lineage appearence date)')

```

## correlation Cases new lineages....
```{r}

covid <- read.csv('../figures/covid-19.csv')
library(zoo)
#covid <- covid[covid$iso_code == 'OWID_WRL',]
covid$Date <- anytime::anydate(covid$date)
covid$YM <- zoo::as.yearmon(anytime::anydate(covid$date))
ggplot(data = covid, aes(x=Date, y=covid$new_cases_per_million))+
  facet_wrap(.~continent, scales='free')+
  geom_smooth()
```


## LIFE SPAN

```{r}
# make dates as days
## get appearance of lineage by cont
f_app <- lineage %>%
  group_by(Nextstrain_clade) %>%
  arrange(Date) %>%
  filter(row_number()==1 )

f_app <- f_app[c('Date','Nextstrain_clade')]
colnames(f_app) <- c('App','Nextstrain_clade')

lineages <- merge(lineage, f_app)

lineages$day <- lineages$Date - lineages$App

ggplot(lineages , aes( x=day, color=continent ))+
  facet_wrap(.~Nextstrain_clade, scales = 'free')+
  geom_density()


selected <- c('20B','20A',
              '20I (Alpha,V1)', 
              '20H (Beta, V2)', '21I (Delta)', 
              '21J (Delta)',
              '21K (Omicron)', '21L (Omicron)', 
              '22B (Omicron)', '22E (Omicron)' )

ggplot(lineages[lineages$Nextstrain_clade %in% selected, ] , aes( x=day ))+
  facet_wrap(.~Nextstrain_clade, scales = 'free', ncol=3)+
  geom_density(alpha=.05,aes( color=continent,  fill=continent))+
  geom_density(color = 'black', linetype='dashed',   adjust = 1.5)+
  labs(x='Time (days)',y='Distribution')

Aflineages <- lineages[lineages$continent=='Africa',]
Aslineages <- lineages[lineages$continent=='Asia',]
SAlineages <- lineages[lineages$continent=='South America',]
```

## LIFE SPAN

```{r}
# make dates as days
## get appearance of lineage by cont
f_app <- lineage %>%
  group_by(Nextstrain_clade) %>%
  arrange(Date) %>%
  filter(row_number()==1 )

f_app <- f_app[c('Date','Nextstrain_clade')]
colnames(f_app) <- c('App','Nextstrain_clade')

lineages <- merge(lineage, f_app)

lineages$day <- lineages$Date - lineages$App


lineages_life <- lineages %>%
                  group_by(Nextstrain_clade, continent) %>%
                  summarise(Mean=mean(day), Max=max(day), Min=min(day), Median=median(day), Std=sd(day))

lineages_lifeM <- merge(lineages_life, f_app)

ggplot(lineages_lifeM, aes(x=App, y=Median, color=continent))+
  geom_smooth(se=FALSE)+
  geom_point()

library(ggrepel)
ggplot(lineages_lifeM, aes(x=App, y=Median))+
  facet_wrap(.~continent, scales = 'free')+
  geom_smooth(se=FALSE)+
  geom_text_repel(aes(label=Nextstrain_clade,color=Nextstrain_clade),size=3)+
  geom_point(aes(label=Nextstrain_clade,color=Nextstrain_clade),size=1)+
  labs(x='Clade First Identification', y='Clade Lifespan')


```

# MUTATIONAL Escape
```{R}
escp <- unique(read.csv('../data/mut_escape.csv'))
mutations <- read.csv('../data/aa_mutations.csv', header=FALSE)
colnames(mutations)[1] = 'id'
library(reshape2)
mutation <- melt(mutations, 'id')[c('id','value')]
colnames(mutation) <- c('gisaid_epi_isl','Mutation')

Mutations <- merge(mutation, escp)
Mutation <- merge(Mutations, samples, by='gisaid_epi_isl')
Mutation <- unique(Mutation[c('Nextstrain_clade','Mutation','mut_escape')])
Mutation <- Mutation[! is.na(Mutation$mut_escape), ]

MutationEscp <- Mutation %>% 
        group_by(Nextstrain_clade) %>% 
        summarise(ESCAPE = sum(mut_escape))

MutEscp <- merge(f_app, MutationEscp)


ggplot(MutEscp, aes(x=App, y=ESCAPE))+
  geom_smooth(se=FALSE, color = 'black', linetype='dashed', method='lm')+
  geom_point()+
  geom_text_repel(aes(label=Nextstrain_clade,color=Nextstrain_clade),size=3)+
  geom_point(aes(label=Nextstrain_clade,color=Nextstrain_clade),size=1)+
  labs(x='Clade First Identification', y='Clade Mutational Escape')


```
## DIvergence
```{R}
samples <- read.csv2('../figures/samples_full.tsv',sep='\t')
div <- samples[c('gisaid_epi_isl','date','divergence')]
div <- unique(div)
div$Date <- anytime::anydate(div$date)


ggplot(div, aes(x=Date, y=as.numeric(divergence)))+
  geom_point(size=.01)+
  geom_smooth(se=FALSE, color = 'blue',method='loess')+
  labs(x='Date', y='Divergence')


ggplot(div, aes(x=zoo::as.yearmon(Date), y=as.numeric(divergence)))+
  geom_point(size=.01)+
  geom_boxplot(aes(group=zoo::as.yearmon(Date)))+
  geom_smooth(se=FALSE, color = 'blue',method='loess')+
  labs(x='Date (Month)', y='Divergence')


```



## Escape
```{R}
samples <- read.csv2('../figures/samples_full.tsv',sep='\t')

escp <- unique(read.csv('../data/mut_escape.csv'))
mutations <- read.csv('../data/aa_mutations.csv', header=FALSE)
colnames(mutations)[1] = 'id'
library(reshape2)
mutation <- melt(mutations, 'id')[c('id','value')]
colnames(mutation) <- c('gisaid_epi_isl','Mutation')

Mutations <- merge(mutation, escp)
Mutation <- merge(Mutations, samples, by='gisaid_epi_isl')
Mutation <- unique(Mutation[c('Nextstrain_clade','Mutation','mut_escape')])
Mutation <- Mutation[! is.na(Mutation$mut_escape), ]

Mutation$mut_escape
Mutation <- Mutation[Mutation$Nextstrain_clade!='recombinant',]

ggplot(Mutation, aes(y=Nextstrain_clade, x=mut_escape, fill=Mutation))+
  geom_col()+
  scale_colour_gradient2()+
  labs('Escape Score','Clade')+
  theme_bw()

Mutation$mut_escape
LINeX <- unique(Mutation) %>%
        group_by(Nextstrain_clade)%>% 
        summarise(S=sum(as.numeric(mut_escape)))

table(Mutation$Nextstrain_clade)

LIN <- samples[c('Nextstrain_clade','divergence')]
LinDiv <- merge(LIN , Mutation)
LinDiv$divergence
library(dplyr)
LINe <- LinDiv %>%
        group_by(Nextstrain_clade)%>% 
        summarise(Median=median(as.numeric(divergence)))

LinMt <- merge(LINe, Mutation)

ggplot(LinMt, aes(y=reorder(Nextstrain_clade , +Median), x=mut_escape, fill=Median))+
  geom_col()+
  scale_colour_gradient2()+
  labs('Escape Score','Clade')+
  theme_bw()


LINe <- LinDiv %>%
        group_by(Nextstrain_clade)%>% 
        summarise(Median=median(as.numeric(divergence)))

```
