---
title: "Mutations"
output: html_document
date: '2023-01-23'
---
```{r}
#installed.packages('ggplot2')
library('ggplot2')
library(dplyr)
library(tidyverse)
library(anytime)
#library(WDI)
theme_set(theme_bw())
library(reshape2)
```


# Distribution
```{r}
md <- read.csv('../data/Metadata.tsv',sep='\t')
subs <- read.csv(header=FALSE, '../data/subs.csv')
colnames(subs)[1] = 'id'
subs <- melt(subs, 'id')[c('id','value')]
colnames(subs) <- c('gisaid_epi_isl','Mutation')
length(unique(subs$Mutation))

muts <- read.csv(header=FALSE, '../data/mutations.csv')
colnames(muts)[1] = 'id'
aaM <- melt(muts, 'id')[c('id','value')]
colnames(aaM) <- c('gisaid_epi_isl','Mutation')
length(unique(aaM$Mutation))

# Split
gene_mut <- aaM %>%
  separate(Mutation, c("Gene", "Mutation"), ":")
gene_mut <- unique(gene_mut[c("Gene", "Mutation")])
gene_mut <- gene_mut[gene_mut$Gene!='',]
ggplot(gene_mut, aes(x = Gene, fill = Gene))+
  geom_bar()+ 
  labs(x='Gene', y='Number of Amino Acid Mutations')

FQ <- as.data.frame(table(gene_mut$Gene))


#ggplot(gene_mut, aes(y = Gene, fill = Gene, x = 1))+
#  geom_bar()+ ggplot2::coord_polar()+
#  labs(x='Gene', y='Number of Amino Acid Mutations')

gene_mut[gene_mut$Gene=='ORF1a', ]$Gene <- 'ORF1ab'
gene_mut[gene_mut$Gene=='ORF1b', ]$Gene <- 'ORF1ab'

ggplot(gene_mut, aes(x = factor(1), fill = factor(Gene))) +
  geom_bar(width = 1)+
  scale_fill_brewer(palette="Spectral")+  coord_polar(theta = "y")+
  theme_void()
FQ$Freq <- FQ$Freq/ sum(FQ$Freq)

gene_mut$pos <- as.numeric(as.character(str_extract(gene_mut$Mutation, "[0-9]+")))
spikes <- gene_mut[gene_mut$Gene == 'S' ,]
ggplot(spikes, aes(x = pos))+
  geom_histogram(aes(y = ..density..), binwidth = 1, fill='#333333')+
  geom_density(adjust = .05, color = 'white', size=2)+
  geom_density(adjust = .05, color = 'blue', size=1)+
  theme_void()


ggplot(spikes, aes(x = pos))+
  geom_histogram(aes(y = ..density..), binwidth = 1, fill='#333333')+
  geom_density(adjust = .5, color = 'red', size=2)


ggplot(spikes[spikes$pos<500,], aes(x = pos))+
  geom_histogram(aes(y = ..density..), binwidth = 1, fill='#333333')+
  geom_density(adjust = .5, color = 'red', size=2)

spikesC <- as.data.frame(table(as.integer(spikes$pos/10)))

gene_mut_fq <- aaM %>%
  separate(Mutation, c("Gene", "Mutation"), ":")
gene_mut_fq <- gene_mut_fq[gene_mut$Gene!='',]
gene_mut_fq$pos <- as.numeric(as.character(str_extract(gene_mut_fq$Mutation, "[0-9]+")))
spikes <- gene_mut_fq[gene_mut_fq$Gene == 'S' ,]

ggplot(spikes, aes(x = pos))+
  geom_histogram(aes(y = ..density..), binwidth = 1, fill='#000000')+
  geom_density(adjust = .5, color = 'red', size=1)
```


```{r}
colnames(aaM) <- c('strain', 'Mutation')
M <- merge(md, aaM, by='strain')
Mm <- M[c('Mutation','Nextstrain_clade')]
Mmd <- as.data.frame(table(Mm))
Mmd <- Mmd[Mmd$Mutation!='',]
Mmd <- Mmd[Mmd$Freq>0,]

Mf <- as.data.frame(table(  unique(M[c('strain','Nextstrain_clade')])$Nextstrain_clade   ))
colnames(Mf) <- c('Nextstrain_clade','N')

#Mf <- Mf[Mf$Nextstrain_clade != 'recombinant',]

MM <- merge(Mf, Mmd)
MM$p <- MM$Freq / MM$N
MMs <- MM[MM$p > .95 , ]
length(unique(MMs$Mutation))
MM_clades <- MM
MMp <- MM[MM$Mutation %in% MMs$Mutation , ]


mut_matrix <- dcast(MMp, Nextstrain_clade~Mutation, value.var="p",fill = 0)

rownames(mut_matrix) <- mut_matrix[,1]
mut_matrix <- mut_matrix[,-1]
mut_matrix_Clade <- mut_matrix
mut_matrix2 <- mut_matrix[, colSums(mut_matrix) > 4.95]


pheatmap::pheatmap(mut_matrix2,
                       border_color = 'white',
                        cluster_cols = FALSE, cluster_rows = TRUE,
                   color = rev(hcl.colors(50, "Spectral") ) )



```
### RECS
```{r}


recs <-  md[md$Nextstrain_clade == 'recombinant',]
table(recs$pango_lineage)

M <- merge(recs, aaM, by='strain')
Mm <- M[c('Mutation','pango_lineage')]
Mmd <- as.data.frame(table(Mm))
Mmd <- Mmd[Mmd$Mutation!='',]
Mmd <- Mmd[Mmd$Freq>0,]

Mf <- as.data.frame(table(  unique(M[c('strain','pango_lineage')])$pango_lineage   ))
colnames(Mf) <- c('pango_lineage','N')

#Mf <- Mf[Mf$Nextstrain_clade != 'recombinant',]

MM <- merge(Mf, Mmd)
MM$p <- MM$Freq / MM$N
MMs <- MM[MM$p > .95 , ]
length(unique(MMs$Mutation))

MM_rec <- MM
MMp <- MM[MM$Mutation %in% MMs$Mutation , ]


mut_matrix <- dcast(MMp, pango_lineage~Mutation, value.var="p",fill = 0)

rownames(mut_matrix) <- mut_matrix[,1]
mut_matrix <- mut_matrix[,-1]
mut_matrixRec <- mut_matrix

mut_matrix2 <- mut_matrix[, colSums(mut_matrix) > 5.95]


pheatmap::pheatmap(mut_matrix2,
                       border_color = 'white',
                        cluster_cols = FALSE, cluster_rows = TRUE,
                   color = rev(hcl.colors(50, "Spectral") ) )

```


```{r}
colnames(MM_rec) <- colnames(MM_clades)
MMx <- rbind(MM_rec, MM_clades)

MMx <- MMx[MMx$Nextstrain_clade!='recombinant',]
MM_all <- MMx
length(unique(MM_all$Mutation))
MMs <- MMx[MMx$p > .95 , ]
length(unique(MMs$Mutation))
MMp <- MMx[MMx$Mutation %in% MMs$Mutation , ]


mut_matrix <- dcast(MMp, Nextstrain_clade~Mutation, value.var="p",fill = 0)

rownames(mut_matrix) <- mut_matrix[,1]
mut_matrix <- mut_matrix[,-1]
mut_matrix_Clade <- mut_matrix
mut_matrix2 <- mut_matrix[, colSums(mut_matrix) > 4.95]


pheatmap::pheatmap(mut_matrix2,
                       border_color = 'white',
                        cluster_cols = FALSE, cluster_rows = TRUE,
                   color = rev(hcl.colors(50, "Spectral") ) )

```

```{r}
library(igraph)
library(ggplot2)

# Load the similarity matrix
C <- cor(t(mut_matrix2))
mat <- as.matrix(C)

# Convert to a graph object
diag(mat) <- 0
g <- graph.adjacency(mat, weighted = TRUE)

#g <- graph.adjacency(mat, mode = "upper", threshold = 0.7, weighted = TRUE)
dF <- igraph::as_data_frame(g)
dF <- dF[dF$from <= dF$to, ]

dfg <- dF[dF$weight>.50,]

write.csv(dfg, '../dfg.csv')


colors <- read.csv('../color_s.csv')
 

```
# Divergence
```{r}


div <- md[c('divergence','date')]
div$Date <- anytime::anydate(div$date)

div$YQ <- zoo::as.yearqtr(div$Date)
library('smplot2')
div$Y <- lubridate::year(div$Date)
div <- div[div$Date > anytime::anydate('2020') , ]
div <- div[div$Date < anytime::anydate('2023') , ]

x <- div[ lubridate::year(div$Date) == lubridate::year(anytime::anydate('2020')) , ]
lm(divergence ~ Date, data=x )

x <- div[ lubridate::year(div$Date) == lubridate::year(anytime::anydate('2021')) , ]
lm(divergence ~ Date, data=x )

x <- div[ lubridate::year(div$Date) == lubridate::year(anytime::anydate('2022')) , ]
lm(divergence ~ Date, data=x )



ggplot(div, aes(Date, divergence, color=as.factor(Y)))+
  geom_point(size=.01)+
  geom_smooth(aes( group=Y), method='lm', color='white', fullrange=TRUE, se=FALSE, size=1.5) +
  geom_smooth(aes( group=Y), method='lm', fullrange=TRUE, se=FALSE, linetype='dashed') +
  geom_smooth(aes( group=Y), method='lm', fullrange=FALSE, se=FALSE) +
  sm_statCorr() +
  scale_color_brewer(palette="Set1")+  
#  geom_smooth(method='lm', color='black') +
  ggplot2::coord_cartesian(y=c(0,NA))
```
```{r}
samples$Nextstrain_clade
Samples <- md[c('strain','Nextstrain_clade')]
muts <- merge(aaM, Samples)
muts <- muts[muts$Mutation!='',]
muts_f <- as.data.frame(table(muts[c('Mutation','Nextstrain_clade')]))
muts_f <- muts_f[muts_f$Freq>0,]
clade_f <- as.data.frame(table(md$Nextstrain_clade))
colnames(clade_f) <- c('Nextstrain_clade','N')

Mmuts <- merge(muts_f, clade_f)
Mmuts$p <- Mmuts$Freq/Mmuts$N
Mmuts$Mutation <- as.character(Mmuts$Mutation)

Mmuts <- Mmuts %>% filter(str_detect(Mutation, "^S"))

selected_mt <- unique(Mmuts[Mmuts$p >.95, 'Mutation'])
Mmutss <- Mmuts[Mmuts$Mutation %in% selected_mt, ]
Mmutss <- Mmutss[Mmutss$Nextstrain_clade!='recombinant',]
Mmutss$p <- as.numeric(Mmutss$p)
mut_matrix <- dcast(Mmutss, Nextstrain_clade~Mutation, value.var="p",fill = 0)
rownames(mut_matrix) <- mut_matrix[,1]

mut_matrix <- mut_matrix[,-1]

ord <- gsub('[A-Z]','',colnames(mut_matrix))
ord <- gsub(':','',ord)
ord <- str_extract(ord, "^[0-9]*")
ord <- as.numeric(ord)
mut_matrix <- mut_matrix[,order(ord)]


MTX <- as.matrix(mut_matrix)

pheatmap::pheatmap(MTX,cluster_cols = FALSE, cluster_rows = FALSE, fontsize_row=8, fontsize_col=8)

```



### SELECT FIRST APP
# Mutation country
```{R}

AA <- read_csv('AA.csv')
AA$YM <- zoo::as.yearmon(AA$date)
mutation_region <- AA[c('Mutation','continent', 'country','date','YM')]
mutation_region <- mutation_region[mutation_region$Mutation!='',]

mutation_region_count <- as.data.frame(table(mutation_region[c('YM','country')]))

n_sample_by_region <- unique(AA[c('gisaid_epi_isl','YM','country')])
n_sample_by_region <- as.data.frame(table(n_sample_by_region[c('YM','country')]))
colnames(n_sample_by_region) <- c('YM','country','Nsamples')

mutation_region_counts <- merge(n_sample_by_region, mutation_region_count)
mutation_region_counts$Nmutation <- mutation_region_counts$Freq / mutation_region_counts$Nsamples

REGIONS <- unique(samples[,c('country','continent')])

mutation_region_counts <- merge(mutation_region_counts, REGIONS)

ggplot(mutation_region_counts, aes(x = as.numeric(YM), y = Nmutation, color = continent))+
 # geom_point(size=.5)+
  geom_boxplot(aes(x =YM ) )+
#  geom_smooth(se=FALSE, size=.5, span=.9)+
  facet_wrap(.~continent, ncol=1)


```
```{R}

app_mut <- mutation_region %>%
  group_by(Mutation) %>%
  arrange(date) %>%
  filter(row_number()==1 )

app_mut_reg <- as.data.frame(table(app_mut[c('continent','YM')]))
samples$date <- anytime::anydate(samples$date)
samples$YM <- zoo::as.yearmon(samples$date)
sample_per_cont <- as.data.frame(table(samples[c('continent','YM')]))

colnames(app_mut_reg) <- c('continent','YM','Nsample')
colnames(sample_per_cont) <- c('continent','YM','SamplesCont')
app_mut2 <- merge(sample_per_cont , app_mut_reg)

app_mut2$Frequency <- app_mut2$Nsample / app_mut2$SamplesCont

mutation_app_reg <- dcast(app_mut2[c('YM','continent','Frequency')],  continent ~ YM, fill = 0)
rownames(mutation_app_reg) <- mutation_app_reg[,1]
mutation_app_reg <- mutation_app_reg[,-1]
pheatmap::pheatmap(as.matrix(mutation_app_reg),cluster_cols=FALSE,cluster_rows=FALSE, color=colorRampPalette(c("skyblue", "lightyellow","pink"))(50))
```

############# BY COUNTRY

```{r}
samples <- read.csv2('../data/all_samples.tsv', sep='\t', header = TRUE)
aa <- read.csv2('../data/aa_mutations.csv', sep=',', header = FALSE)
colnames(aa)[1] = 'id'




library(reshape2)
aaM <- melt(aa, 'id')[c('id','value')]
colnames(aaM) <- c('gisaid_epi_isl','Mutation')

AA <- merge(aaM,samples,by = 'gisaid_epi_isl')


mutation_region <- AA[c('Mutation','country','date')]
mutation_region <- mutation_region[mutation_region$Mutation!='',]
mutation_region$date <- anytime::anydate(mutation_region$date)
mutation_region$YM <- zoo::as.yearmon(mutation_region$date)
mutation_region_count <- as.data.frame(table(mutation_region[c('YM','country')]))

AA$YM <- zoo::as.yearmon(anytime::anydate(AA$date))
n_sample_by_region <- unique(AA[c('gisaid_epi_isl','YM','country')])
n_sample_by_region <- as.data.frame(table(n_sample_by_region[c('YM','country')]))
colnames(n_sample_by_region) <- c('YM','country','Nsamples')

mutation_region_counts <- merge(n_sample_by_region, mutation_region_count)
mutation_region_counts$Nmutation <- mutation_region_counts$Freq / mutation_region_counts$Nsamples
mutation_region_counts <- mutation_region_counts[mutation_region_counts$Nsamples>0,]


app_mut <- mutation_region %>%
  group_by(Mutation) %>%
  arrange(date) %>%
  filter(row_number()==1 )

app_mut_reg <- as.data.frame(table(app_mut$country))
colnames(app_mut_reg) <- c('country','Nmutation')

samples_country <- as.data.frame(table(samples$country))
colnames(samples_country) <- c('country','Samples')

app_mut_reG <- merge(app_mut_reg, samples_country)
app_mut_reG$freq <- app_mut_reG$Nmutation / app_mut_reG$Samples

library(rworldmap)
joinData <- rworldmap::joinCountryData2Map( app_mut_reG,
                                 joinCode = "NAME",
                                 nameJoinColumn = "country")

colourPalette <- rev(RColorBrewer::brewer.pal(11,'Spectral'))
mapCountryData( joinData, nameColumnToPlot="freq", addLegend=TRUE , colourPalette=colourPalette)
mapCountryData( joinData, nameColumnToPlot="freq")

```

`

### LINEAGE FIRST APP

```{R}


#AA <- read_csv('AA.csv')
samples <- unique(samples)
samples$YM <- zoo::as.yearmon(anytime::anydate(samples$date))
lineage_region <- samples[,c('pango_lineage','continent','date','YM')]
lineage_region <- lineage_region[lineage_region$pango_lineage!='',]
lineage_region <- unique(lineage_region)
lineage_region_count <- as.data.frame(table(lineage_region[c('YM','continent')]))

n_sample_by_region <- unique(samples[c('gisaid_epi_isl','YM','continent')])
n_sample_by_region <- as.data.frame(table(n_sample_by_region[c('YM','continent')]))
colnames(n_sample_by_region) <- c('YM','continent','Nsamples')

lineage_region_counts <- merge(n_sample_by_region, lineage_region_count)
lineage_region_counts$Nlineages <- lineage_region_counts$Freq / lineage_region_counts$Nsamples


app_lin <- lineage_region %>%
  group_by(pango_lineage) %>%
  arrange(date) %>%
  filter(row_number()==1 )

app_lin_reg <- as.data.frame(table(app_lin[c('continent','YM')]))
samples$date <- anytime::anydate(samples$date)
samples$YM <- zoo::as.yearmon(samples$date)
sample_per_cont <- as.data.frame(table(samples[c('continent','YM')]))

colnames(app_lin_reg) <- c('continent','YM','Nsample')
colnames(sample_per_cont) <- c('continent','YM','SamplesCont')
app_lin2 <- merge(sample_per_cont , app_lin_reg)

app_lin2$Frequency <- app_lin2$Nsample / app_lin2$SamplesCont

app_lin_reg <- dcast(app_lin2[c('YM','continent','Frequency')],  continent ~ YM, fill = 0)
rownames(app_lin_reg) <- app_lin_reg[,1]
app_lin_reg <- app_lin_reg[,-1]

app_lin2$Frequency
ggplot(app_lin2, aes(as.numeric(YM) , Frequency, color = continent))+
  geom_point()+
  geom_smooth(se=FALSE, span=.9)


############# BY COUNTRY


pango_lineage_region <- samples[c('pango_lineage','country','date')]
pango_lineage_region <- pango_lineage_region[pango_lineage_region$pango_lineage!='',]
pango_lineage_region$date <- anytime::anydate(pango_lineage_region$date)
pango_lineage_region$YM <- zoo::as.yearmon(pango_lineage_region$date)
pango_lineage_region_count <- as.data.frame(table(pango_lineage_region[c('YM','country')]))

samples$YM <- zoo::as.yearmon(anytime::anydate(samples$date))
n_sample_by_region <- unique(samples[c('gisaid_epi_isl','YM','country')])
n_sample_by_region <- as.data.frame(table(n_sample_by_region[c('YM','country')]))
colnames(n_sample_by_region) <- c('YM','country','Nsamples')

pango_lineage_region_counts <- merge(n_sample_by_region, pango_lineage_region_count)
pango_lineage_region_counts$Npango_lineage <- pango_lineage_region_counts$Freq / pango_lineage_region_counts$Nsamples
pango_lineage_region_counts <- pango_lineage_region_counts[pango_lineage_region_counts$Nsamples>0,]


app_mut <- pango_lineage_region %>%
  group_by(pango_lineage) %>%
  arrange(date) %>%
  filter(row_number()==1 )

app_mut_reg <- as.data.frame(table(app_mut$country))
colnames(app_mut_reg) <- c('country','Npango_lineage')

samples_country <- as.data.frame(table(samples$country))
colnames(samples_country) <- c('country','Samples')

app_mut_reG <- merge(app_mut_reg, samples_country)
app_mut_reG$freq <- app_mut_reG$Npango_lineage / app_mut_reG$Samples

app_mut_reG <- app_mut_reG[app_mut_reG$Samples>10, ]
library(rworldmap)
joinData <- rworldmap::joinCountryData2Map( app_mut_reG,
                                 joinCode = "NAME",
                                 nameJoinColumn = "country")

colourPalette <- rev(RColorBrewer::brewer.pal(11,'Spectral'))

m <- mapCountryData( joinData, nameColumnToPlot="freq", colourPalette=colourPalette, addLegend=FALSE)


do.call( addMapLegend, c( m
                          , legendLabels="all"
                          , legendWidth=0.5 ))
```



```{r}
app_mut_regg <- merge(app_mut_reG, REGIONS)
app_mut_regg$
ggplot(app_mut_regg, aes(x=continent, fill=continent, y=freq))+
  geom_boxplot()




lineage_per_country <- app_mut_regg[,c('country','freq','continent')]

gdp <- read.csv('../data/gdp.csv',sep=',')
gdp <- gdp[c('Country.Name','X2021')]
colnames(gdp) <- c('country','gdp')
lineages_gdp <- merge(lineage_per_country, gdp)
ggplot(lineages_gdp, aes(x = gdp, y = freq, color = continent))+
  geom_point()+
  facet_wrap(.~continent, ncol = 1, scales = 'free')+
  coord_cartesian(ylim=c(0, NA), xlim=c(0, NA), expand = FALSE)+
  geom_smooth(method = 'glm', se= FALSE, fullrange= TRUE)




pop <- read.csv('../data/pop.csv',sep=',')
pop <- pop[c('Country.Name','X2021')]
colnames(pop) <- c('country','pop')
lineages_pop <- merge(lineage_per_country, pop)
ggplot(lineages_pop, aes(x = pop, y = freq, color = continent))+
  geom_point()+
  facet_wrap(.~continent, ncol = 1, scales = 'free_x')+
  coord_cartesian(ylim=c(0, NA), expand = FALSE)+
  geom_smooth(method = 'glm', se= FALSE, fullrange= TRUE)


hiv <- read.csv('../data/hiv.csv',sep=',')
hiv <- hiv[c('Country.Name','X2021')]
colnames(hiv) <- c('country','hiv')
lineages_hiv <- merge(lineage_per_country, hiv)
ggplot(lineages_hiv, aes(x = hiv, y = freq, color = continent))+
  geom_point()+
  facet_wrap(.~continent, ncol = 1, scales = 'free_x')+
  coord_cartesian(ylim=c(0, NA), expand = FALSE)+
  geom_smooth(method = 'glm', se= FALSE, fullrange= TRUE)

```


### Clinical data
```{r}
cov <- read.csv2('../data/covid-19.csv', sep=',')
cov = cov[cov$total_cases > 0,]
cov <- cov[,c('continent',"location","date","total_cases","new_cases","total_deaths","new_deaths","new_cases_per_million","total_deaths_per_million","new_deaths_per_million","total_cases_per_million","new_tests","tests_per_case","new_tests_per_thousand","total_tests","total_tests_per_thousand")]


Cov <- cov %>%
  group_by(location) %>%
  arrange(total_tests_per_thousand) %>%
  filter(row_number()==n() )

Cov$total_tests_per_thousand <- as.numeric(Cov$total_tests_per_thousand)
Cov <- Cov[! is.na(Cov$total_tests_per_thousand), ]


CCov <- Cov %>%
  group_by(continent) %>%
  summarise(M = median(total_tests_per_thousand) )



ggplot(Cov , aes(continent, total_tests_per_thousand, color = continent, fill = continent))+
  geom_boxplot(outlier.shape = NA, alpha = .3)+
  scale_y_continuous(limits = quantile(Cov$total_tests_per_thousand, c(0.1, 0.9)))+
  geom_jitter()+
  ggrepel::geom_text_repel(aes(label=location), size = 4,  min.segment.length = 0) + 
  labs(x= 'Geographic region', y = 'Total tests per thousands (1/1/2023)')
```
```{r}

md$continent <- md$region
pango_lineage_region <- md[c('gisaid_epi_isl','pango_lineage','continent','country','date')]
aa <- read.csv2('../data/aa_mutations.csv', sep=',', header = FALSE)
colnames(aa)[1] = 'id'
library(reshape2)
aaM <- melt(aa, 'id')[c('id','value')]
colnames(aaM) <- c('gisaid_epi_isl','Mutation')

AAp <- merge(aaM,pango_lineage_region,by = 'gisaid_epi_isl')
AAp <- AAp[AAp$Mutation!='',]
AAp$p <- 1
AAp$continent
AApc <- AAp[c('pango_lineage', 'continent')]
AApc <- unique(AApc)
AAc <- dcast(AAp, pango_lineage~Mutation, value.var="p",fill = 0)
rownames(AAc) <- AAc$pango_lineage
AAc <- AAc[,-1]
head(AAc)


AAp$date <- anytime::anydate(AAp$date)
AAp1 <- AAp %>%
  group_by(pango_lineage) %>%
  arrange(date) %>%
  filter(row_number()==1 )

LinCont <-unique( AAp1[c('pango_lineage', 'continent')])
length(unique(LinCont$pango_lineage))

cnt <- c('Africa', 'Asia','Europe','North America','Oceania','South America')
colors = c('#ff7675', '#a29bfe','#74b9ff','#55efc4','#fdcb6e','#00b894')

Colors <- as.data.frame(cnt)
Colors$color <- colors
Colors$continent <- cnt
LinCont1 <- merge(LinCont , Colors)
write.csv(LinCont1, 'LinCont1.csv')

corrLineages <- cor(t(AAc))
CorL <- melt(corrLineages)
CorLL <- CorL[CorL$value>.9,]

CorL <- CorL[CorL$Var1!=CorL$Var2, ]
CorL1 <- CorL %>%
  group_by(Var1) %>%
  arrange(value) %>%
  filter(row_number()==n() | row_number()==n()-1)

CorL1 <- CorL1[CorL1$value>0,]

library(igraph)
str(CorL1)
colnames(CorL1) <- c('source', 'target', 'weight')
# Create the graph object from dataframe
g <- igraph::graph_from_data_frame(CorL1, directed = FALSE, vertices = NULL)


V(g)$color <- LinCont1$color[match(V(g)$name, LinCont1$pango_lineage)]

# Plot the graph
plot(g, edge.width = E(g)$weight, vertex.size = 2, layout = layout_with_fr, vertex.label.cex = 0.7, vertex.label.color = V(g)$color  )
write.graph(g, "graph2.graphml", format = "graphml")
  getwd()

```


# NETWORK


```{r}
#md <- read.csv('../data/all_samples.tsv',sep='\t')
md <- read.csv('../data/all_samples.tsv',sep='\t')
md <- unique(md)

md$YM <- zoo::as.yearmon(anytime::anydate(md$date))
md$region <- md$continent
table(md$region)

ym_f <- as.data.frame(table(md[,c('YM','region')]))
ym_f$YM <- zoo::as.yearmon(as.character(ym_f$YM))
str(ym_f)

ggplot(ym_f, aes(x=YM,Freq, fill=region))+
  geom_bar(stat = 'identity')+
  labs(x = 'Date (month)',y = ' Number of Sequences')

md$continent <- md$region
pango_lineage_region <- md[c('gisaid_epi_isl','Nextstrain_clade','continent','country','date')]
aa <- read.csv2('../data/aa_mutations.csv', sep=',', header = FALSE)
colnames(aa)[1] = 'id'
library(reshape2)
aaM <- melt(aa, 'id')[c('id','value')]
colnames(aaM) <- c('gisaid_epi_isl','Mutation')

AAp <- merge(aaM,pango_lineage_region,by = 'gisaid_epi_isl')
AAp <- AAp[AAp$Mutation!='',]
AAp$p <- 1
AAp$continent
AApc <- AAp[c('Nextstrain_clade', 'continent')]
AApc <- unique(AApc)
AAp$p <- 1
AAc <- dcast(AAp, Nextstrain_clade~Mutation, value.var="p",fill = 0)
rownames(AAc) <- AAc$Nextstrain_clade
AAc <- AAc[,-1]
head(AAc)


AAp$date <- anytime::anydate(AAp$date)
AAp1 <- AAp %>%
  group_by(Nextstrain_clade) %>%
  arrange(date) %>%
  filter(row_number()==1 )


```

```{r}
LinCont <-unique( AAp1[c('Nextstrain_clade', 'continent')])
LinCont <- LinCont[LinCont$Nextstrain_clade!='recombinant',]
length(unique(LinCont$Nextstrain_clade))

cnt <- c('Africa', 'Asia','Europe','North America','Oceania','South America')
colors = c('#ff7675', '#a29bfe','#74b9ff','#55efc4','#fdcb6e','#00b894')

Colors <- as.data.frame(cnt)
Colors$color <- colors
Colors$continent <- cnt
LinCont1 <- merge(LinCont , Colors)
write.csv(LinCont1, 'LinCont1.csv')

corrLineages <- cor(t(AAc))



CorL <- melt(corrLineages)
CorL <- CorL[CorL$Var1!='recombinant',]
CorL <- CorL[CorL$Var2!='recombinant',]
CorLL <- CorL[CorL$value>.95,]

CorL <- CorL[CorL$Var1!=CorL$Var2, ]

#CorL <- CorL1
CorL1$value <- CorL1$weight
CorL1 <- CorL1[CorL1$value>0,]

library(igraph)
str(CorL1)
colnames(CorL1) <- c('source', 'target', 'weight')
CorL1 <- CorL1[c('source', 'target', 'weight')]
# Create the graph object from dataframe
g <- igraph::graph_from_data_frame(CorL1, directed = FALSE, vertices = NULL)


V(g)$color <- LinCont1$color[match(V(g)$name, LinCont1$Nextstrain_clade)]

# Plot the graph
plot(g, edge.width = E(g)$weight, vertex.size = 2, layout = layout_with_fr, vertex.label.cex = 0.7, vertex.label.color = V(g)$color  )
write.graph(g, "graph_clades95.graphml", format = "graphml")
  getwd()

```

## Transmission network
```{r}
Sample_region <- AAp
AAp$gisaid_epi_isl
selected_samples <- AAp[,c('gisaid_epi_isl','Nextstrain_clade','country')]


selected_samples <- AAp %>%
      group_by(Nextstrain_clade,country) %>%
      arrange(date) %>%
      filter(row_number()==1 ) 



PPa <- AAp[AAp$gisaid_epi_isl%in% selected_samples$gisaid_epi_isl , ]

Sample_mut <- unique(PPa[c('Mutation','gisaid_epi_isl')])
Sample_mut$p <- 1

count <- as.data.frame(table(Sample_mut$Mutation))
selected <- count[count$Freq>1 , ]$Var1
length(selected)

Sample_mut <- Sample_mut[Sample_mut$Mutation %in% selected, ]
Sample_muts <- dcast(Sample_mut, gisaid_epi_isl~Mutation, value.var="p", fill=0)

rownames(Sample_muts) <- Sample_muts[,1]
Sample_muts <- Sample_muts[,-1]
#Sample_muts <- Sample_muts[ , colSums (Sample_muts)>5]

Sample_muts <- unique(Sample_muts)


Cor <- cor(t(Sample_muts))

library(igraph)
#str(CorL1)
#CorL1 <- CorL1[CorL1$weight> .9, ]
# Create the graph object from dataframe
```
`
```{r}
CorL1 <- melt(Cor)
colnames(CorL1) <- c('source', 'target', 'weight')
CorL1 <- CorL1[! is.na(CorL1$weight),]
CorL1 <- CorL1[CorL1$source!=CorL1$target, ]
head(CorL1)

CorL1 <- CorL1[CorL1$weight>0,]
#CorL1 <- CorL1[CorL1$weight>0.5,]

Corel <- CorL1 %>%
  group_by(source) %>%
  arrange(weight) %>%
  filter(row_number()>(n()-1)) # select top 10

Corel <- Corel[Corel$weight>0.75,]


#Corel <- CorL1 
#rm(CorL1)
#Corel <- Corel[Corel$weight>0,]

rm(CorL1)
g <- igraph::graph_from_data_frame(Corel, directed = FALSE, vertices = NULL)
Sample_region <- Sample_region[c('gisaid_epi_isl','continent')]


Sample_region <- Sample_region[c('gisaid_epi_isl','continent')]


Sample_clade <- unique(PPa[,c('gisaid_epi_isl','Nextstrain_clade')])
rownames(Sample_clade) <- Sample_clade$gisaid_epi_isl


continent <- c('Africa','Asia','Europe','North America','Oceania','South America' )
continent_color <- as.data.frame(continent)
continent_color$colors <- c('red','green','cyan','yellow','blue','purple' )

Sample_region <- merge(Sample_region, continent_color)

Sample_region <- unique(Sample_region)
rownames(Sample_region) <- Sample_region$gisaid_epi_isl

Sample_cats <- Sample_region[V(g)$name ,]
Sample_clds <- Sample_clade[V(g)$name ,]

Sample_clds <- Sample_clade[ V(g)$name,]

V(g)$color <- Sample_cats$colors
V(g)$continent <- Sample_cats$continent
V(g)$Nextstrain_clade <- Sample_clds$Nextstrain_clade

write.graph(g, "Transmissiongraph03.graphml", format = "graphml")


plot(g, 
     labels = FALSE,
     vertex.label='',
     vertex.size=2,
     layout=igraph::layout.kamada.kawai
     )


plot(g, 
     labels = FALSE,
     vertex.label='',
     vertex.size=2,
     layout=igraph::layout.spring
     )



```


```{r}
CldCount <- AAp1[c('Nextstrain_clade','country')]
CldCount$color = '1'
joinData <- rworldmap::joinCountryData2Map( CldCount,
                                 joinCode = "NAME",
                                 nameJoinColumn = "country")

colourPalette <- (RColorBrewer::brewer.pal(31,'Spectral'))
rworldmap::mapCountryData( joinData, nameColumnToPlot="color", addLegend=FALSE, colourPalette=colourPalette )
#mapCountryData( joinData, nameColumnToPlot="freq")


ggplot(data = CldCount, aes(Nextstrain_clade, country, fill = Nextstrain_clade))+
  geom_path()+
  ggrepel::geom_label_repel(color='white',aes(label=Nextstrain_clade))

```


#Corelation age divergence
```{r}
patients <- read.csv('../ncov/data/Sequences_Metadata.tsv',sep='\t')
patients <- unique(patients)
patients <- patients[c('gisaid_epi_isl','sex','age')]

md <- read.csv('../data/Metadata.tsv',sep='\t')

rec$age
rec <- read.csv('../data/rec.tsv',sep='\t')
rec$Nextstrain_clade

mean(md$age)

mean(rec$age)

ggplot(data=rec, aes(x=age))+
  geom_density()

rec$YM <- lubridate::year(anytime::anydate(rec$date))
rec$region
rec_f <- as.data.frame(table(rec[c('YM','age','region','sex')]))
rec_f <- rec_f[rec_f$Freq>0,]
#rec_f$YM <- zoo::as.yearqtr(anytime::anydate(rec_f$YM))
rec_f$age <- as.numeric(rec_f$age)
ggplot(data=rec_f, aes(x=YM, y= Freq , fill=age, fill=sex))+
  geom_bar(stat='identity')+
  facet_wrap(.~sex)
  
CladeF <- as.data.frame(table(rec[c('age','Nextstrain_clade')]))
RegF <- as.data.frame(table(rec[c('region','Nextstrain_clade')]))
SxF <- as.data.frame(table(rec[c('sex','Nextstrain_clade')]))

md$continent <- md$region
sequences <- unique(md)

md <- merge(patients, sequences)
md$age <- as.numeric(md$age)
md <- md[! is.na(md$age),]

ageDiv <- md
clades <- c('19B','','','','','','','','','','','','','','')
#RemoveClades <- c('20F','21B (Kappa)','recombinant','20D','20H (Beta, V2)','21C (Epsilon)','20E (EU1)','22F (Omicron)','','','','','','','')
ageDiv <- ageDiv[! ageDiv$Nextstrain_clade%in%RemoveClades,]


ageDiv$region
CORs <- plyr::ddply(ageDiv, .(Nextstrain_clade,region), summarise, "corr" = cor(age, divergence, method = "spearman"))

CORs <- CORs[ ! is.na(CORs$corr), ]

aggregate( region ~ ., CORs, mean )

ggplot(ageDiv[ageDiv$Nextstrain_clade == '22D (Omicron)' , ], aes(age, divergence, color = region))+
  facet_wrap(.~region, scales = 'free_y' )+
  geom_point(size=1)+
  geom_smooth(method='lm')+
  geom_smooth(method='lm', fullrange=TRUE, linetype='dashed', se=FALSE)

```

```{r}
patients <- read.csv('../ncov/data/Sequences_Metadata.tsv',sep='\t')

patients <- unique(patients)
patients$Date <- anytime::anydate(patients$date)
patients$SubDate <- anytime::anydate(patients$date_submitted)

patients$date_diff <- difftime(patients$date, patients$date_submitted)
patients$D <- as.numeric( patients$SubDate ) - as.numeric(patients$Date)

aggregate( region ~ ., patients, mean )

ggplot(patients , aes(D, region, color = region))+
  geom_point(width=.2)+
  geom_boxplot(fill='white')+
  labs(x='Submission Delay (Days)',y='Continent')

```